config/routes.rb
Pollster::Application.routes.draw do

  resources :polls do
    member do
      get 'results'
    end
  end
  
  resources :answers
  
  root :to => 'polls#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :question_id, :content, :author

  validates :content, :presence => { :message => "is required for submission" }

  belongs_to :question
  delegate :poll, :to => :question
end

app/models/poll.rb
class Poll < ActiveRecord::Base
  attr_accessible :author, :title, :created_at, :questions_attributes

  validates :title, :uniqueness => true, :presence => { :message => "A poll name is required" }
  validates :author, :presence => { :message => "An author is required" }

  has_many :questions, :dependent => :destroy

  accepts_nested_attributes_for :questions, :reject_if => lambda { |q| q[:title].blank? }, :allow_destroy => true
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :title
  belongs_to :poll

  has_many :answers, :dependent => :destroy

  accepts_nested_attributes_for :answers, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def create
    question = Question.find(params[:answer].delete(:question_id))
    unless answered_questions.include?(question.id)
      @answer = question.answers.new(params[:answer])
      if @answer.save
        answered_questions << @answer.question_id
      else
        flash[:error] = @answer.errors.to_a.join(', ')
      end
    end
    redirect_to poll_path(question.poll)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :answered_questions
  
  after_filter :save_cookie

  private

  def answered_questions
    @answered_questions ||= if cookies[:answered_questions]
      cookies[:answered_questions].split(";").collect(&:to_i)
    else
      []
    end
  end

  def save_cookie
    # cookies[:answered_questions] << 
    cookies[:answered_questions] = answered_questions.join(";")
    #     # "1;5;7;3"
  end
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController

  def index
    @polls = Poll.all
  end

  def show
    @poll = Poll.find(params[:id])
  end

  def update
    @poll = Poll.find(params[:id])

    if @poll.update_attributes(params[:poll])
      redirect_to @poll, notice: 'Poll was successfully updated.' 
    end
  end

  def edit
    @poll = Poll.find(params[:id])
  end

  def new
    @poll = Poll.new
  end

  def create
    @poll = Poll.new(params[:poll])
    @poll.save

    if @poll.save
      redirect_to polls_path, notice: 'Poll was successfully created.'
    else
      render action: "new" 
    end
  end

  def results
    @poll = Poll.find(params[:id])
  end

end


# add define question types
# add different answer fields depending on types
# not showing all questions in vote after adding remove tag
# add admin pages
# add author to answers
# add validations
# if no questions, destroy poll (or show an error page)
# add poll editing index for admin (last addition)
# add notices for delete and add

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def create
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def link_to_remove_fields(name, f)
    f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)")
  end

  def link_to_add_fields(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render(association.to_s + "_fields", :f => builder)
    end
    
    link_to_function(name, "add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")")
  end
end

app/helpers/polls_helper.rb
module PollsHelper
  def already_answered?(question)
    answered_questions.include? question.id
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
<head>
	<meta charset="utf-8" />
	
	<!-- Uncomment to make IE8 render like IE7 -->
	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->
	
	<!-- Set the viewport width to device width for mobile -->
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	
	<title>Pollster</title>
	<%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>
  <div class="container">
    <div class="row">
      <div class="six columns centered">
        <h1>
          <%= link_to 'Pollster', '/', id: "logo" %>
        </h1>

        <% if flash[:error] %>
          <div class="alert-box alert">
            <row> <%= flash[:error] %></row>
            <a href="" class="close">&times;</a>
          </div>
        <%end %>

        <%= yield %>
        
      </div> 
    </div>
  </div>
</body>
</html>

app/views/polls/_answer_fields.html.erb
<p>
  <%= f.label :content, "Answer" %>
  <%= f.text_field :content %>
</p>

app/views/polls/_form.html.erb
<%= form_for(@poll) do |f| %>

  <% @poll.errors.each_with_index do |msg, i| %>
    <div class="alert-box alert">
      <row><%= msg[1] %></row>
      <a href="" class="close">&times;</a>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title, :class => "left inline" %>
    <%= f.text_field :title, :class => "twelve" %>
  </div>

  <div class="field">
    <%= f.label :author, :class => "left inline"  %>
    <%= f.text_field :author, :class => "twelve"  %>
  </div>

  <%= f.fields_for :questions do |builder| %>
    <%= render "questions_fields", :f => builder %>
  <% end %>

  <p><%= link_to_add_fields "Add Question", f, :questions  %></p>

  <div class="actions">
    <%= f.submit "Add poll", :class => "button", :id => "new_poll" %>
  </div>

<% end %>

app/views/polls/_questions_fields.html.erb
<p class="fields">
  <p><%= f.label :title, "Question" %><p>
  <%= f.text_field :title %>
  <%= f.hidden_field :_destroy %>

  <%= link_to_remove_fields "remove", f %>
</p>

app/views/polls/edit.html.erb
<h3>New Poll</h3>

<%= form_for(@poll) do |f| %>

  <div class="field">
    <%= f.label :title, :class => "left inline" %>
    <%= f.text_field :title, :class => "twelve" %>
  </div>

  <div class="field">
    <%= f.label :author, :class => "left inline"  %>
    <%= f.text_field :author, :class => "twelve"  %>
  </div>

  <%= f.fields_for :questions do |builder| %>
    <%= render "questions_fields", :f => builder %>
  <% end %>

  <p><%= link_to_add_fields "Add Question", f, :questions %></p>

  <div class="actions">
    <%= f.submit "Update poll", :class => "button" %>
  </div>

<% end %>

app/views/polls/index.html.erb
<%= button_to 'New Poll', new_poll_path, :method => :get,  :class => 'button', :id => 'new_poll'  %>

<ul class="accordion">
  <% @polls.each do |poll| %>
    <li>

      <div class="title">
        <h5><%= poll.title %></h5>
      </div>

      <div class="content">
      
        
        <row>
        <span class="grey">
          <%= poll.author %> created this poll <%=  distance_of_time_in_words_to_now(poll.created_at.to_date) %> ago
        </span>
        <br> 
        <span class="grey">
          <span class="count"><%= "#{poll.questions.count}" %></span> questions
        </span>
        <%= link_to "Vote", poll, class: "small button right" %>
        <%= link_to "Results", results_poll_path(poll.id), class: "secondary small button right" %>
        </row>

      </div>
    </li>
  <% end %>
</ul>

app/views/polls/new.html.erb
<h3>New Poll<h3>

<%= render 'form' %>

app/views/polls/results.html.erb
<h3>Results for 
  <%= @poll.title %>
</h3>

<% @poll.questions.each do |question| %>
  <hr>
  <h4 class="subheader"><%= question.title %></h4>

  <% question.answers.each do |answer| %>
    <p><%= answer.content %><p>
  <% end %>
<% end %>

<%= link_to "Pollster Home", "/", :class => "secondary button", :id => "full_width" %>

app/views/polls/show.html.erb
<h3><%= @poll.title %></h3>

<% @poll.questions.each do |question| %>
  <% unless already_answered?(question) %>
    <p><%= question.title %></p>
      

    <div class="row collapse">
      <div class="ten mobile-three columns">
        <%= form_for question.answers.new, class: "form" do |f| %>
        <%= f.hidden_field :question_id %>
        <%= f.text_field :content %>
      </div>
      <div class="two mobile-one columns">

            <%= f.submit "Submit", :class => "button expand postfix" %>
            <% end %>
      </div>
    </div>
  <% end %>
<% end %>

<% if already_answered? @poll.questions.last %>
  <p>You've answered this poll. See the results <%= link_to "here!", results_poll_path %></p>
<% end %>

<%= link_to "Pollster Home", "/", :class => "secondary button", :id => "new_poll" %>
<%= link_to "View Results", results_poll_path, :class => "button", :id => "full_width" %>